task:
  environment:
    TELEGRAM_TOKEN: ENCRYPTED[847ddb079d484d13518d2e4c2ade68f5a275e77244624b106286f2a044260280f7b026914729590b8485689b5674514b]
    TELEGRAM_CHAT: ENCRYPTED[64dee47565224fc565f425a5e933411fcfb578bca824f49168136c256a89de34f466be5f1b373cf4730cf7059b3295cc]
    GIT_TOKEN: ENCRYPTED[be2f375d25b726cc4726889a52eb63d178cd2659f91777a161da80f8e14628337e999fd227578b48c54ab86a942bd49e]
    TC: ryz
  name: Build Kernel
  timeout_in: 2h
  container:
      image: panchajanya1999/archlinux:latest
      cpu: 4
      memory: 16G

  Build_script:
      - echo "LC_ALL=en_US.UTF-8" | sudo tee -a /etc/environment
      - echo "en_US.UTF-8 UTF-8" | sudo tee -a /etc/locale.gen
      - echo "LANG=en_US.UTF-8" | sudo tee -a /etc/locale.conf
      - sudo locale-gen en_US.UTF-8
      - wget https://raw.githubusercontent.com/ryz-code/my-script/master/ci/build.sh
      - bash build.sh 12.1/main