env:
    token: "ENCRYPTED[7303401155ce6381cf4bff8323e518d4ed8c32e35b858b2225eb3e645aaf1299d346f1b1afbcb26031268fb92b3c11cf]"
    chat_id: "ENCRYPTED[3ce8813da1a085315e4379b25a495ed15c1ecaeb502e76a598d855a3d002b3a55e69dba33d87c7343906dd11c16d8766]"
    
task:
  name: "Kernel deploy.."
  timeout_in: 120m
  container:
      image: z4nyx/docker:latest
      cpu: 4
      memory: 16G
      stateful: true
      greedy: true

  Build_script:
      - git clone --depth=1 -b t13 https://github.com/itsshashanksp/kernel_xiaomi_sm6150 lv && cd lv
      - bash build.sh --proton
