env:
    token: "ENCRYPTED[7303401155ce6381cf4bff8323e518d4ed8c32e35b858b2225eb3e645aaf1299d346f1b1afbcb26031268fb92b3c11cf]"
    chat_id: "ENCRYPTED[f8c4b12e20e3c946fc5e79bef8d6e2d479a1a589839b09764f7a77299314043a54887b55c323c4e297149437ee7bcc25]"
    
task:
  name: "Kernel deploy.."
  timeout_in: 120m
  container:
      image: z4nyx/docker:latest
      cpu: 4
      memory: 16G
      stateful: true
      greedy: true

  Build_script:
      - git clone --depth=1 -b t13 https://github.com/ryz-code/kernel_xiaomi_sm6150 lv && cd lv
      - bash build.sh --proton
